name: Build MicroPython RP2 (HID)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BOARD: RPI_PICO2_W
      PICO_SDK_PATH: ${{ github.workspace }}/micropython/ports/rp2/pico-sdk
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clone MicroPython source
        run: |
          git clone https://github.com/micropython/micropython.git
          cd micropython
          git submodule update --init --recursive

      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y cmake gcc-arm-none-eabi build-essential python3 python3-pip git patch

      - name: Setup pico-sdk
        run: |
          if [ ! -d "${PICO_SDK_PATH}" ]; then
            git clone https://github.com/raspberrypi/pico-sdk.git "${PICO_SDK_PATH}"
            (cd "${PICO_SDK_PATH}" && git submodule update --init)
          fi

      - name: Apply HID patch
        run: |
          cd micropython
          git apply ../patches/mpconfigport.h.patch || true

      - name: Build MicroPython
        run: |
          cd micropython/ports/rp2
          make clean || true
          make submodules
          make BOARD="${BOARD}" V=1
          echo "=== Listando build dir ==="
          ls -lah "build-${BOARD}" || true
          echo "=== Procurando UF2 ==="
          find "build-${BOARD}" -name '*.uf2' -maxdepth 2

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware-uf2
          path: |
            micropython/ports/rp2/build-${{ env.BOARD }}/*.uf2
          if-no-files-found: error
